### ISSUE TITLE
How do I submit solutions for questions from 2 onwards on Coursemology?

### ISSUE THREAD

**Issue by joulev** [nus-cs2113-AY2223S2/forum#2]
<img width="559" alt="image" src="https://user-images.githubusercontent.com/44609036/212438944-3c2084ce-954d-40ab-97c4-577fced65ef4.png">

When I attempted it, the numbers from 2 to 4 were greyed out and could not be clicked on. In the many buttons down below, none of them contains the text like "Move to next question" either. It made me think the quiz only has one question, which I know is wrong once I submitted the attempt.

So what should I do to submit code for question 2 onwards?

If someone hasn't attempted, could you add a screenshot of that here as well (I have submitted so I cannot go back to that screen anymore).

Edit: If you didn’t receive the invitation link, see #3.

**Comment by T-Wan-Lin** [comment]
Hello, I am having the same problem and I think it might be because I clicked "Finalise Submission" thinking it was finalising the submission per question attempted but it finalised the submission for all the questions, attempted or not. 

If that's the case, is it possible for the admin side to void my submission? Thank you!

**Comment by L0Z1K** [comment]
~Did you get invitation link of Coursemology? I didn't receive that email now. :(~
It was in my spam..

**Comment by avielcx** [comment]
i clicked finalise submission as well. How do we rectify?

**Comment by Thiolk** [comment]
I encounter the same problem as well where i finalise my submission after the first question

**Comment by darrenangwx** [comment]
> Hello, I am having the same problem and I think it might be because I clicked "Finalise Submission" thinking it was finalising the submission per question attempted but it finalised the submission for all the questions, attempted or not.
> 
> If that's the case, is it possible for the admin side to void my submission? Thank you!

I did this as well. I thought it was submission for question 1. but it submitted the whole 1 to 4.

**Comment by xiaoge26** [comment]
I finalised my submission as well after the first question ;-; I thought it was for question 1 only...

**Comment by EangJS** [comment]
I did this as well. I thought it was submission for question 1. but it submitted from 1 to 4.

**Comment by joulev** [comment]
Hi everyone, perhaps it’s a bit late by now already, but [it’s a bad idea to comment “+1” or “same problem” or similar](https://github.com/orgs/community/discussions/4921) in GitHub issues. Please use reactions (emotes) instead.

**Comment by okkhoy** [comment]
Please drop me a note with your full name; I will unsubmit your attempts. 
(I have received a few requests and helped them out)

**Comment by joulev** [comment]
@okkhoy My full name is Vu Van Dung. Thank you.

**Comment by Thiolk** [comment]
@okkhoy my full name is Thio Leng Kiat, thank you

**Comment by calebcjl** [comment]
@okkhoy Full name: Caleb Chan Jia Le
Thank you Prof

**Comment by okkhoy** [comment]
Done. I have unsubmitted your attempt.
Please remember to submit once you complete all exercises for your attempt to be recorded.

Thanks,
Akshay

**Comment by Koh-Jing-Jie-Marcus** [comment]
Full name: Koh Jing Jie Marcus
thanks prof

**Comment by okkhoy** [comment]
@Koh-Jing-Jie-Marcus you haven't submitted yet; so nothing for me to do. please complete all 4 and submit

**Comment by T-Wan-Lin** [comment]
@okkhoy Full name: Tan Wan Lin

Thank you so much and sorry for the inconvenience!

**Comment by Ju-Can** [comment]
@okkhoy full name: Ju Can
Thank you!

**Comment by azriellee** [comment]
@okkhoy full name: Lee Tze Weng Azriel
Thanks prof!

**Comment by LimHongYao** [comment]
@okkhoy full name: Lim Hong Yao
sorry about the trouble and thanks!

**Comment by saintzaw** [comment]
@okkhoy full name: Saint Thiri Zaw
thanks prof!

**Comment by okkhoy** [comment]
@T-Wan-Lin @Ju-Can  @azriellee @LimHongYao @saintzaw  

Done. I have unsubmitted your attempt.
Please remember to submit once you complete all exercises for your attempt to be recorded.

Thanks,
Akshay

**Comment by BernardLesley** [comment]
@okkhoy full name: Bernard Lesley Efendy
I finalized my submission after the first question also. Thank you, prof!

**Comment by okkhoy** [comment]
@BernardLesley 

Done. I have unsubmitted your attempt.
Please remember to submit once you complete all exercises for your attempt to be recorded.

Thanks,
Akshay

**Comment by Koh-Jing-Jie-Marcus** [comment]
Full name: Koh Jing Jie Marcus
Thanks prof

**Comment by okkhoy** [comment]
@Koh-Jing-Jie-Marcus 

Done. I have unsubmitted your attempt.
Please remember to submit once you complete all exercises for your attempt to be recorded.

Thanks,
Akshay

**Comment by ZiqiuZeng** [comment]
@okkhoy Full name: Zeng Ziqiu 
Thank you prof:)

**Comment by okkhoy** [comment]
@ZiqiuZeng 

Done. I have unsubmitted your attempt.
Please remember to submit once you complete all exercises for your attempt to be recorded.

Thanks,
Akshay

**Comment by stephenkyang** [comment]
@okkhoy  Full name: Yang Stephen Ka Ming

Sorry about that, thank you professor!

**Comment by Geeeetyx** [comment]
@okkhoy Full name: Tan Yu Xiang, Gareth

Thank you prof

**Comment by joulev** [comment]
Since we are at week 3 and can access Week 4 quiz already, I will close this issue. Anyone having issues with the submissions are still welcome to post messages here but I doubt there is anyone like that now.
