### ISSUE TITLE
Do I need to create a branch for all A-* tags after A-Packages?

### ISSUE THREAD

**Issue by joulev** [nus-cs2113-AY2223S2/forum#25]
<img width="714" alt="image" src="https://user-images.githubusercontent.com/44609036/216802299-0cabe95b-05fb-4bba-9e4a-80f6c7cef3cc.png">

From the screenshot I see that creating `branch-A-Packages` is only recommended, not *required* (hence I didn't do it).

However, does the same apply for future `A-*` tags? Or do I need to create branches for each of those tags?

**Comment by joulev** [comment]
From [this](https://nus-cs2113-ay2223s1.github.io/dashboards/contents/ip-progress.html) (last sem dashboard)

<img width="785" alt="image" src="https://user-images.githubusercontent.com/44609036/216802705-d23a0ca3-9a56-4d5f-b1ac-dfb65f6d09e0.png">

I suppose some tags require branches while some tags don't.

**Comment by okkhoy** [comment]
Anything marked `optional` is optional. Everything else requires you to follow the instructions.
E.g.,
![image](https://user-images.githubusercontent.com/1023494/216875923-f750d4d6-a87f-4210-a5ac-969978b06948.png)

**Comment by joulev** [comment]
Understood, thank you.
