### ISSUE TITLE
Didn't Receive Invitation for Coursemology

### ISSUE THREAD

**Issue by imdxz** [nus-cs2113-AY2223S2/forum#3]
On the Course Website, it wrote:

> You'll receive the invitation to Coursemology sometime close to the first lecture.  

But I haven't received an invitation yet. Would you be able to send me the invitation again? Thanks.

**Comment by joulev** [comment]
It went to my spam folder yesterday at 22:50. You might want to check your NUS email spam folder.

**Comment by imdxz** [comment]
I also found it in my spam folder lol. Thank you!
