### ISSUE TITLE
Cannot Access Catcher

### ISSUE THREAD

**Issue by woowenjun99** [nus-cs2113-AY2223S2/forum#40]
I tried to re-enter catcher with the same GitHub account and they asked if I want to continue as my GitHub account which I clicked, but it showed that I am an unauthorised user. Does this mean that I will not be able to edit the catcher again after the smoke test is done?

<img width="683" alt="Screenshot 2023-03-24 at 9 53 55 AM" src="https://user-images.githubusercontent.com/88195289/227404731-f4df2763-23cb-4d45-bb00-b088f5650245.png">

**Comment by okkhoy** [comment]
pls select cs2113/ alpha test as the session and try
