### ISSUE TITLE
Request to use PC Part Picker data from web scraping

### ISSUE THREAD

**Issue by Magmanat** [nus-cs2113-AY2223S2/forum#44]
## Library

PC Part Picker website unofficial API

## Purpose

Scrape data for our pc parts tp application

https://github.com/JonathanVusich/pcpartpicker

**Comment by okkhoy** [comment]
Please explain how you plan to use it in your tP?
@Magmanat

**Comment by Magmanat** [comment]
@okkhoy It is mainly to just scrape data for existing PC parts such as CPU's, GPU's along with their specifications. This data will be used in a json file which will load into the application

**Comment by okkhoy** [comment]
Ok, noted on the usecase. I think I saw that the API has things to do with checking part compatibility etc., which may be what you want to do. Then I would be concerned about the depth of your tP.
Would still like you to ping me on MSTeams (create a group chat with your team and tutor).

**Comment by okkhoy** [comment]
Resolved over messages on MSTeams. This thread is no-longer applicable.
@Magmanat please reopen if you still need permission to use this.
